version: '3.8'

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    ports:
      - "8089:80"
      - 8090:443
      - 1935:1935
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${HOST_VOLUME_PATH:-.}/traefik/certs:/certs/"
      - "${HOST_VOLUME_PATH:-.}/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
      - "${HOST_VOLUME_PATH:-.}/traefik/dynamic.yaml:/config/dynamic.yaml"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal
      - traefik.docker.network=traefik-ingress
    networks:
      - traefik-ingress
    restart: unless-stopped
networks:
  traefik-ingress:
    external: true
