version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.x.x
    ports:
      - "8554:8554"
      # - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "9997:9997"
      # - "8890:8890/udp"
      # - "8189:8189/udp"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    stdin_open: true
    tty: true
    restart: unless-stopped
