version: "3.2"
services:
  ######## mongo db ###########
  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    environment:
      - MONGODB_ROOT_PASSWORD=xxxx
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=phongthien
      - MONGODB_DATABASE=tdss
    ports:
      - "27017:27017"
    # volumes:
    #   - 'mongodb_data:/bitnami/mongodb'
    restart: always