services:
  s3manager:
    container_name: s3manager
    image: cloudlena/s3manager
    ports:
      - 9091:8080
    environment:
      - ENDPOINT=
      - ACCESS_KEY_ID=
      - SECRET_ACCESS_KEY=
      - REGION=
      - USE_SSL=true
      - BUCKET=
 
  